/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type SchemaVersion = 1;
export type Id = string;
export type Title = string;
export type Description = string | null;
export type Kind = "general" | "course";
/**
 * @minItems 1
 */
export type Questions = [Question, ...Question[]];
export type Id1 = string;
export type Number = number;
export type Text = string;
export type SchemaVersion1 = 1;
export type Id2 = string | null;
export type Status = "draft" | "verified";
export type Course = string;
/**
 * @minItems 1
 */
export type General = [string, ...string[]];
export type Pairs = CrosswalkPair[];
export type SchemaVersion2 = 1;
export type Slug = string;
export type Title1 = string;
export type Language = string;
/**
 * @minItems 1
 */
export type QuestionSets = [string, ...string[]];
export type VideoId = string;
export type Url = string;
export type Title2 = string;
export type DurationS = number | null;
export type Order = number;
export type Sources = Source[];
export type SchemaVersion3 = 1;
export type VideoId1 = string;
export type Source1 = "whisper" | "captions";
export type Model = string | null;
export type Language1 = string;
export type Start = number;
export type End = number;
export type Text1 = string;
export type Segments = Segment[];
export type ChunkId = string;
export type SourceType = "video";
export type VideoId2 = string;
export type Start1 = number;
export type End1 = number;
export type Text2 = string;
export type SchemaVersion4 = 1;
export type QuestionId = string;
export type Candidates = number;
export type ChunkId1 = string;
export type Relevance = number;
/**
 * @minItems 1
 */
export type Points = [string, ...string[]];
export type Quote = string;
export type Relevant = RelevantChunk[];
export type Text3 = string;
export type ChunkId2 = string;
export type Readings = ExtractReading[];
export type Model1 = string;
export type PromptVersion = string;
export type InputHash = string;
export type SchemaVersion5 = 1;
export type QuestionId1 = string;
export type QuestionSet1 = string;
export type Question1 = string;
export type AnswerMd = string;
export type OutsideLecturesMd = string | null;
export type N = number;
export type ChunkId3 = string;
export type VideoId3 = string;
export type Start2 = number;
export type Quote1 = string;
export type Citations = Citation[];
export type Text4 = string;
export type VideoId4 = string;
export type Start3 = number;
export type Readings1 = AnswerReading[];
export type Coverage = "full" | "partial" | "not_found";
export type Model2 = string;
export type PromptVersion1 = string;
export type InputHash1 = string;
export type GeneratedAt = string;
export type Error = string | null;
export type SchemaVersion6 = 1;
export type Slug1 = string;
export type Title3 = string;
export type Language2 = string;
export type QuestionSets1 = string[];
export type Videos = number;
export type QuestionId2 = string;
export type QuestionSet2 = string;
export type Coverage1 = "full" | "partial" | "not_found";
export type Citations1 = number;
export type Answers = IndexAnswer[];
export type Courses = IndexCourse[];
export type QuestionSets2 = QuestionSet[];
export type Crosswalks = Crosswalk[];
export type GeneratedAt1 = string;

export interface ExamprepData {
  QuestionSet?: QuestionSet;
  Crosswalk?: Crosswalk;
  Course?: Course1;
  Transcript?: Transcript;
  Chunk?: Chunk;
  Extract?: Extract;
  Answer?: Answer;
  DataIndex?: DataIndex;
}
export interface QuestionSet {
  schema_version: SchemaVersion;
  id: Id;
  title: Title;
  description: Description;
  kind: Kind;
  questions: Questions;
}
export interface Question {
  id: Id1;
  number: Number;
  text: Text;
}
/**
 * Hand-made topic mapping between a course set and the general set.
 *
 * Advisory only: it drives the "related questions" links in the UI and never
 * takes part in retrieval.
 */
export interface Crosswalk {
  schema_version: SchemaVersion1;
  id: Id2;
  status: Status;
  pairs: Pairs;
}
export interface CrosswalkPair {
  course: Course;
  general: General;
}
export interface Course1 {
  schema_version: SchemaVersion2;
  slug: Slug;
  title: Title1;
  language: Language;
  question_sets: QuestionSets;
  sources: Sources;
}
export interface Source {
  video_id: VideoId;
  url: Url;
  title: Title2;
  duration_s: DurationS;
  order: Order;
}
export interface Transcript {
  schema_version: SchemaVersion3;
  video_id: VideoId1;
  source: Source1;
  model: Model;
  language: Language1;
  segments: Segments;
}
export interface Segment {
  start: Start;
  end: End;
  text: Text1;
}
export interface Chunk {
  chunk_id: ChunkId;
  source_type: SourceType;
  video_id: VideoId2;
  start: Start1;
  end: End1;
  text: Text2;
}
export interface Extract {
  schema_version: SchemaVersion4;
  question_id: QuestionId;
  candidates: Candidates;
  relevant: Relevant;
  readings: Readings;
  model: Model1;
  prompt_version: PromptVersion;
  input_hash: InputHash;
}
export interface RelevantChunk {
  chunk_id: ChunkId1;
  relevance: Relevance;
  points: Points;
  quote: Quote;
}
/**
 * A work the lecturer named out loud, with the fragment that mentions it.
 */
export interface ExtractReading {
  text: Text3;
  chunk_id: ChunkId2;
}
export interface Answer {
  schema_version: SchemaVersion5;
  question_id: QuestionId1;
  question_set: QuestionSet1;
  question: Question1;
  answer_md: AnswerMd;
  outside_lectures_md: OutsideLecturesMd;
  citations: Citations;
  readings: Readings1;
  coverage: Coverage;
  model: Model2;
  prompt_version: PromptVersion1;
  input_hash: InputHash1;
  generated_at: GeneratedAt;
  error: Error;
}
export interface Citation {
  n: N;
  chunk_id: ChunkId3;
  video_id: VideoId3;
  start: Start2;
  quote: Quote1;
}
export interface AnswerReading {
  text: Text4;
  video_id: VideoId4;
  start: Start3;
}
/**
 * ``data/index.json`` — the only file the site has to fetch first.
 *
 * Question sets are inlined: all of them together are a few dozen kilobytes,
 * and the browser then needs neither a YAML parser nor a second round trip.
 */
export interface DataIndex {
  schema_version: SchemaVersion6;
  courses: Courses;
  question_sets: QuestionSets2;
  crosswalks: Crosswalks;
  generated_at: GeneratedAt1;
}
export interface IndexCourse {
  slug: Slug1;
  title: Title3;
  language: Language2;
  question_sets: QuestionSets1;
  videos: Videos;
  answers: Answers;
}
/**
 * What the pipeline has already produced for one question of one course.
 */
export interface IndexAnswer {
  question_id: QuestionId2;
  question_set: QuestionSet2;
  coverage: Coverage1;
  citations: Citations1;
}
